### PR TITLE
Feature/120 code coverage codecov

### PR DESCRIPTION
**Pull request by dwdraju**

### CODE REVIEW

**Comment by sink772** [comment]
@dwdraju It's weird that "Code Coverage with Codecov" check succeeds, despite some failures in the go test.
Can you check and fix the script not to pass the check condition when the go test fails?

**Review by sink772 — CHANGES_REQUESTED** [review]
@dwdraju It's weird that "Code Coverage with Codecov" check succeeds, despite some failures in the go test.
Can you check and fix the script not to pass the check condition when the go test fails?

**Comment by dwdraju** [comment]
> @dwdraju It's weird that "Code Coverage with Codecov" check succeeds, despite some failures in the go test. Can you check and fix the script not to pass the check condition when the go test fails?

Hi @sink772, I have created a [PR for the fix](https://github.com/icon-project/goloop/pull/122). Please review.

**Comment by sink772** [comment]
Yeah... now code coverage check is failing due to the Go test has failed.

To pass the Go test, this branch needs to be rebased to master tip, since we've pushed some patches to resolve the data race problems.

**Pull request merged**
