### PR TITLE
conditionally strip BOM mark for generating public key from keystore

### PR DESCRIPTION
**Pull request by robcxyz**
Relates to #170

### CODE REVIEW

**Comment by mksong76** [comment]
According to https://www.rfc-editor.org/rfc/rfc7159#section-8.1
> Implementations MUST NOT add a byte order mark to the beginning of a JSON text.

So, theoretically, it doesn't need to handle it.

**Comment by robcxyz** [comment]
Yeah I was a little confused about it as well but it was the only way to get it to parse. I posted this in the telegram channel and at least one other person reported the same error.

**Comment by sink772** [comment]
The keystore file you tried should be the one that your goloop node was using. So I don't understand why the error occurred. 
I can only assume that the keystore file got corrupted while copying it from the Docker instance.
Anyway, I also think we don't need to handle this.  You need to strip the BOM by other means.

**Comment by robcxyz** [comment]
So the json is parsable with jq and not sure how it could be corrupted beyond that since it is simple text. At least right now, I know of two others that have faced this issue. It is very odd though, I'll admit that.

**Comment by mj-hana** [comment]
We also found the same issue.

**Comment by sink772** [comment]
As we said above, we do not want to handle this issue in goloop directly.  You can strip the BOM by using another tool like `sed`.
```
sed -i '1s/^\xEF\xBB\xBF//' keystore.json
```
https://unix.stackexchange.com/a/381263

**Pull request closed without merging**
