### PR TITLE
change reflected along with cache policy change

### PR DESCRIPTION
**Pull request by dhlee-icon**
- add createIfNotExist option to GetTimer, as cache policy changed

### CODE REVIEW

**Comment by dhlee-icon** [comment]
@inwonkim Please, find the changes in timer and slash parts and check if any side effect is expected to occur.

**Comment by dhlee-icon** [comment]
@inwonkim I reflected your requests to this branch. Could you please review once again?
 
one thing, in iiss.HandleTimerJob, first error can be ignored(or overwritten) by the second one, would that be okay?

**Comment by inwonkim** [comment]
> @inwonkim I reflected your requests to this branch. Could you please review once again?
> 
> one thing, in iiss.HandleTimerJob, first error can be ignored(or overwritten) by the second one, would that be okay?

That's right. need to add handling code for both error state.

**Comment by dhlee-icon** [comment]
@inwonkim I added error handling in iiss.HandleTimerJob and changed method signature of GetAccount(). Please review again.

**Review by inwonkim — APPROVED** [review]

**Pull request merged**
